name: flutter_drawing_board
description: A comprehensive drawing canvas app with collaborative features
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #3D operation
  vector_math: ^2.1.4

  # UI and Icons
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0

  # State Management
  flutter_bloc: ^9.1.1

  # HTTP and WebSocket
  http: ^1.1.0
  web_socket_channel: ^3.0.3

  # Database and Storage
  supabase_flutter: ^2.0.0
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # File Operations
  file_picker: ^10.2.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  permission_handler: ^12.0.0+1
  share_plus: ^7.2.1

  # Environment and Configuration
  flutter_dotenv: ^5.1.0

  # JSON and Serialization
  json_annotation: ^4.8.1

  # Utils
  uuid: ^4.1.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  test: ^1.24.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/svgs/
    - assets/icons/